### PR TITLE
Renaming Done

### LINKED ISSUE #247: Rename all `.yml` to `.yaml` as Officially Recommended
https://yaml.org/faq.html

### PR DESCRIPTION
**Pull request by postmeback**
As suggested in the issue, renamed .yml to .yaml

Fixes #247

### CODE REVIEW

**Review by josecelano — APPROVED** [review]

**Comment by josecelano** [comment]
ACK 3a22aeea307f00fdc5cbf44fce389338782558aa

**Comment by josecelano** [comment]
Thank you, @postmeback, for your first contribution to this repo! Welcome! Apart from the issues, we also have some [discussions](https://github.com/torrust/torrust-index/discussions). And any feedback about current or future features is very welcome.

**Comment by josecelano** [comment]
@postmeback could you [sign the commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)?

**Comment by josecelano** [comment]
> @postmeback could you [sign the commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)?

I've opened a new [PR](https://github.com/torrust/torrust-index/pull/314).

**Comment by postmeback** [comment]
The PR seems to redirect in this page only.

**Comment by josecelano** [comment]
> The PR seems to redirect in this page only.

Hi @postmeback, I pasted the wrong link. [This](https://github.com/torrust/torrust-index/pull/317) is the right one.

**Pull request closed without merging**
