### PR TITLE
Use normal variables instead of secrets for `user` and `repo` on DockerHub

### PR DESCRIPTION
**Pull request by josecelano**
From: `torrust/index-backend:develop`
To: `torrust/index:develop`

### CODE REVIEW

**Comment by josecelano** [comment]
In order to rename the docker image we only need to change the GitHub env variables and trigger the `container` workflow again to publish the image.

But I have made some changes anyway:

image

I've created new env variables for the DockerHub user and repo instead of using secrets. I think we do not need secrets for that and It can help to find errors in the pipeline.

**Review by da2ce7 — APPROVED** [review]
Changed not related to rename, but good refactor anyhow.

**Comment by josecelano** [comment]
> Changed not related to rename, but good refactor anyhow.

Changed.

**Comment by josecelano** [comment]
ACK b93564c3e52c21a909511ad9682b863c8a142592

**Comment by josecelano** [comment]
I've removed the unused secrets:

image

**Pull request merged**
