### PR TITLE
feat: [#303] store in the database the torrent fields creation_date c…

### LINKED ISSUE #303: Store in the database the torrent fields: `creation_date`, `created_by`, `encoding`
Parent issue: https://github.com/torrust/torrust-index-backend/issues/296

### PR DESCRIPTION
**Pull request by mario-nt**
Resolves #303.

### CODE REVIEW

**Review by josecelano — APPROVED** [review]
It looks good!

**Comment by josecelano** [comment]
Hi @mario-nt this needs a rebase. I tried to do it with the GitHub UI, but commits are not verified.

**Comment by mario-nt** [comment]
@josecelano Rebase done and tests OK, we need to update the types and API libs before merging to make this PR work. I will update the types lib and then update the dependencies in the API lib.

**Comment by josecelano** [comment]
> @josecelano Rebase done and tests OK, we need to update the types and API libs before merging to make this PR work. I will update the types lib and then update the dependencies in the API lib.

I've released the new types https://www.npmjs.com/package/torrust-index-types-lib/v/1.0.0-alpha.4

**Comment by mario-nt** [comment]
@josecelano Ready to be merged.

**Pull request merged**
