### PR TITLE
chore: updated cargo dependency toml to 0.8.6

### PR DESCRIPTION
**Pull request by mario-nt**

### CODE REVIEW

**Comment by mario-nt** [comment]
@josecelano

**Comment by josecelano** [comment]
> @josecelano

Hi @mario-nt I can't merge it because the commit is not signed. The rules set requires all commits to be signed:

http://github.com/torrust/torrust-index/rules?ref=refs%2Fheads%2Fdevelop

This is the rule:

https://github.com/torrust/torrust-index/rules/97092?ref=refs%2Fheads%2Fdevelop

**Comment by mario-nt** [comment]
@josecelano Commit signed

**Comment by josecelano** [comment]
ACK 821708f999d31b96176c7b3b724141a9b05063a1

**Pull request merged**
